server:
  port: 8080

spring:
  profiles:
    active: dev
    include:
      - env # ???????? application-env.yml ??????
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # ????
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: 123456
