server:
  port: 8080

spring:
  profiles:
    active: dev
    include:
      - env # 在当前目录下新建 application-env.yml 配置敏感信息
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name} # 驱动名称
    url: ${sky.datasource.url}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  data:
    redis:
      host: ${sky.data.redis.host}
      port: ${sky.data.redis.port}
      password: ${sky.data.redis.password}
      database: ${sky.data.redis.database}
  wechat:
    app-id: ${sky.wechat.appid}
    app-secret: ${sky.wechat.appsecret}





mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.waimai.skypojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast-admin-secret-key-2026-safe!
    # 设置jwt过期时间
    admin-ttl: 86400000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 小程序的jwt配置
    user-secret-key: itcast-user-secret-key-2026-safe!
    user-ttl: 86400000
    user-token-name: authentication

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


 #Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true


#aliyunOss配置
aliyun:
    oss:
        endpoint: ${sky.aliyun.oss.endpoint}
        access-key-id: ${sky.aliyun.oss.access-key-id}
        access-key-secret: ${sky.aliyun.oss.access-key-secret}
        bucket-name: ${sky.aliyun.oss.bucket-name}
