sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动名称
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
  #aliyunOss配置
  aliyun:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5t8yj5XjyXjy
      access-key-secret: <KEY>
      bucket-name: sky-take-out-bucket

  wechat:
    appid: "wx63794ac25f9ded50"
    appsecret: "212bbc7b8f501537de5a439a3779c0a6"